### ISSUE TITLE
Particle system as background

### ISSUE THREAD

**Issue by shinsal** [plattysoft/Leonids#17]
Hi, 

First of all, I would like to thank you for making this library. It's very useful for what I'm trying to achieve.

However, I want all the emitted particles to be in the background instead of the foreground. As of currently I have it, it show a snow-like particles but all those particles will make all my other views in the layout to be in the background. Is there any way to make the particles to be in the background instead?

Anything you can point out to help me with this would be appreciated.

Thanks,

Shinta

**Comment by plattysoft** [comment]
This is something that is not possible, but it is planned.

The idea is that when you create the ParticleField, it can be a child of another view (preferably a FrameLayout) instead of a child of the android.R.id.content, with that you can position it anywhere in your layout.

I plan to do that update soon, probably this week or next week.

**Comment by shinsal** [comment]
I see. Cool!! Thank you for the prompt reply! I look forward to the update to the library.
