### ISSUE TITLE
Can particle system be launched from OpenGL model?

### ISSUE THREAD

**Issue by power7714** [plattysoft/Leonids#31]
I have an OpenGL 3D model in my Android app and I wanted to know if I can create a OneShot particle release upon the user tapping a certain point on the model. Is this possible and if so how? Thank you!

**Comment by plattysoft** [comment]
That should be possible, since you can launch a particle system at a position on the screen, but you need to get the x and y for that.

Now, I do not recommend to use this library if you are already using OpenGL. There are plenty of OpenGL particle systems that have better performance. That was never the intention of this library.
