### ISSUE TITLE
Question : Is there any plan to implement collision detection?

### ISSUE THREAD

**Issue by am5a03** [plattysoft/Leonids#44]
Hi,
Thanks for this library. May I know if there's any plan to add collision detection? :smile:

**Comment by plattysoft** [comment]
I haven't considered adding collision detection, but it should be relatively easy since it the code for collision detection, including quadtree optimization is in the book [Mastering Android Game Development](https://www.packtpub.com/game-development/mastering-android-game-development) and it is also in the [Ballons project](https://github.com/plattysoft/BalloonsGame). Feel free to combine them.

However, collision detection is easy, but it is not very useful unless you combine it with physics, and that is another story completely.

**Comment by am5a03** [comment]
Cool, that leaves me as a challenge! :)
I'll close this issue.
