### ISSUE TITLE
Support for vector drawables

### ISSUE THREAD

**Issue by brinkkemper** [plattysoft/Leonids#57]
Nice library, got me playing playing with the parameters real fast!
I noticed vectors don't work if I pass their resourceId.
Would it be hard to implement it?

**Comment by plattysoft** [comment]
Thanks!

Actually is should be relatively easy. Since essentially the library draws bitmaps, so it is all about creating a Bitmap from the Drawable, as seen here: http://stackoverflow.com/questions/33696488/getting-bitmap-from-vector-drawable

Feel free to do a Pull Request with it. I have almost no time to work on this anymore.
